version: '3.9'

services:
  postgres:
    networks:
      net: null
    container_name: users_container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aboba
      POSTGRES_PASSWORD: aboba
      POSTGRES_DB: registration
    restart: always
    healthcheck:
      test: pg_isready -U aboba -d registration
      interval: 3s
      retries: 5
  tests:
    networks:
      net: null
    container_name: tests
    image: tests
    build:
      ../../../../python_tests/code
    volumes:
      - ../../../../python_tests/code :/tmp/code
    entrypoint: /bin/bash /tmp/code/start_tests.sh
    depends_on:
      postgres:
        condition: service_healthy
  app:
    networks:
      net: null
    image: registration.jar
    ports:
      - "8080:8080"
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    container_name: app
    environment:
      - spring.application.name=registration
      - spring.datasource.url=jdbc:postgresql://postgres:5432/registration
      - spring.datasource.username=aboba
      - spring.datasource.password=aboba
      - server.port=8080
      - spring.freemarker.expose-request-attributes=true
      - spring.jpa.hibernate.ddl-auto=create-drop
      - spring.jackson.serialization.indent_output=true
      - server.error.include-message=always
      - spring.web.resources.add-mappings=true
networks:
  net:
    external:
      name: net